[mqtt]
#mqtt_url=mqtt.wcmesh.com
mqtt_url=mqtt.lincomatic.com
mqtt_port=8883
tls_insecure=y
mqtt_username=wcmesh
mqtt_password=meshcoast
#mqtt_topics = meshcore/+/+/packets
mqtt_topics=  meshcore/LAX/+/packets, meshcore/SAN/+/packets, meshcore/OXR/+/pa\
ckets, meshcore/PSP/+/packets
